import type { Metadata } from "next";
import "./globals.css";

import { Nunito_Sans as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import HeaderSection from "@/components/header-section";
import DesktopSideBar from "@/components/layout/desktop-sidebar";
import Footer from "@/components/footer";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen flex bg-background font-sans antialiased select-text selection:bg-primary selection:text-white",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <HeaderSection />
          <DesktopSideBar/>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
